In [189]:
import numpy as np

In [9]:
array = np.zeros((9,9))

In [14]:
array[:3,:3]

array[3:6,3:6]
array[6:,6:]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [175]:
board = np.zeros((9,9))


for i in range(0,9):
    for j in range(0,9):
        nums_to_try = [1,2,3,4,5,6,7,8,9]
        number_is_not_valid = True
        max_num = 9
        #check if number in position is valid else remove from nums to try
        while number_is_not_valid:
            if max_num>1:
                num = nums_to_try[np.random.randint(0,max_num)]
            else:
                num = nums_to_try[0]
            
            print(max_num)
            #check if nuber is valid
            
            if num in board[i]:
                max_num-=1
                nums_to_try.remove(num)
                
            elif num in board[:,j]:
                max_num-=1
                nums_to_try.remove(num)
                
            else:
                board[i,j] = num
                number_is_not_valid = False
                
        
        

9
9
9
8
9
9
8
9
8
9
8
7
6
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
8
9
9
8
7
6
5
9
8
7
9
8
7
6
9
8
7
6
9
8
7
6
5
4
3
2
9
9
9
8
9
9
8
7
6
5
4
3
9
8
9
8
7
6
9
9
8
9
9
9
8
9
8
7
6
9
8
7
6
9
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
1


IndexError: list index out of range

In [104]:
board

array([[2., 1., 8., 4., 7., 9., 3., 6., 5.],
       [3., 8., 7., 1., 5., 6., 9., 4., 2.],
       [8., 9., 3., 2., 6., 7., 1., 5., 4.],
       [7., 4., 2., 5., 1., 8., 6., 3., 9.],
       [1., 6., 5., 3., 8., 2., 4., 9., 7.],
       [5., 2., 4., 6., 9., 1., 7., 8., 3.],
       [9., 7., 1., 8., 4., 5., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
array[:,1]

array([5., 4., 5., 5., 5., 3., 3., 3., 4.])

In [ ]:
array

In [42]:
nums_to_try.remove(8)

In [43]:
nums_to_try

[1, 2, 3, 4, 5, 6, 7, 9]

In [58]:
array

array([[6., 5., 3., 2., 3., 4., 4., 2., 2.],
       [8., 4., 6., 4., 1., 7., 8., 8., 4.],
       [3., 5., 5., 5., 8., 7., 5., 4., 1.],
       [5., 5., 6., 8., 6., 7., 8., 5., 5.],
       [4., 5., 4., 6., 2., 7., 7., 7., 8.],
       [6., 3., 3., 7., 3., 5., 7., 4., 5.],
       [2., 3., 6., 1., 8., 6., 8., 1., 7.],
       [1., 3., 8., 4., 2., 2., 3., 1., 7.],
       [1., 4., 1., 7., 8., 7., 2., 7., 1.]])

In [61]:
4 in array[:,1]

True

In [72]:
nums_to_try[0]

IndexError: list index out of range

In [73]:
nums_to_try

[]

In [80]:
nums_to_try = [1,2,3,4,5,6,7,8,9]

In [81]:
nums_to_try[8]

9

In [95]:
np.random.randint(0,1)

0

In [177]:
board_made = True
while board_made:
    try:
        board = np.zeros((9,9))
        for i in range(0,9):
            for j in range(0,9):
                nums_to_try = [1,2,3,4,5,6,7,8,9]
                number_is_not_valid = True
                max_num = 9
                
                #check if number in position is valid else remove from nums to try
                while number_is_not_valid:
                    for i in range(0,9):
                        for j in range(0,9):
                            nums_to_try = [1,2,3,4,5,6,7,8,9]
                            number_is_not_valid = True
                            max_num = 9
                            #check if number in position is valid else remove from nums to try
                            while number_is_not_valid:
                                if max_num>1:
                                    num = nums_to_try[np.random.randint(0,max_num)]
                                else:
                                    num = nums_to_try[0]

                                print(max_num)
                                #check if nuber is valid

                                if num in board[i]:
                                    max_num-=1
                                    nums_to_try.remove(num)

                                elif num in board[:,j]:
                                    max_num-=1
                                    nums_to_try.remove(num)

                                else:
                                    board[i,j] = num
                                    number_is_not_valid = False
                
        
        
    except IndexError:
            pass
        
    else:
        board_made=False
            

9
9
9
9
9
9
8
9
9
9
8
7
6
9
8
9
9
9
8
9
8
7
9
9
8
9
9
8
7
6
5
4
3
9
8
9
9
9
8
9
8
9
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
7
6
9
9
9
9
9
9
9
9
9
8
7
6
5
4
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
9
9
8
7
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
8
7
9
9
8
7
6
5
4
3
9
9
8
9
8
9
8
7
9
8
9
8
7
6
9
8
7
6
5
9
9
8
7
6
5
9
8
7
9
9
9
8
7
9
8
9
8
7
9
8
9
8
7
6
5
9
8
7
6
5
4
9
9
8
7
9
9
9
8
7
6
9
8
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
8
9
8
9
9
9
8
9
8
9
9
8
7
6
9
9
8
7
9
9
8
7
6
5
4
3
9
9
9
9
8
7
9
8
7
9
8
7
6
9
8
7
6
5
4
3
2
1
9
8
7
6
5
4
3
2
9
9
9
9
8
7
9
8
7
6
9
9
9
8
7
6
5
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
8
7
9
8
7
9
8
9
8
9
8
7
6
9
9
8
7
6
5
4
3
9
9
8
7
6
9
8
9
8
9
8
7
6
5
9
9
8
7
6
5
4
3
2
9
8
7
6
5
9
8
7
6
9
8
7
6
5
4
3
2
9
8
7
6
9
8
9
8
7
6
5
4
9
8
7
6
5
9
8
7
6
5
9
8
7
9
8
9
8
7
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
9
9
8
7
6
5
9
8
7
6
9
9
9
9
9
8
9
8
9
8
9
8
7
6
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
9
9
9
8
7
6
5
9
9
9
9
8
9
8
7
6
9
9
9
8
7
6
5
4
3
2
1
9
8
7
6
5
9
9
8
9
9
8
7
9
8


9
8
9
8
7
9
8
7
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
8
7
6
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
8
9
8
7
9
9
8
9
8
9
9
8
9
8
9
9
9
9
8
9
8
9
8
9
8
7
6
5
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
8
7
9
8
7
9
8
7
6
9
9
9
9
9
9
9
9
9
8
7
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
9
8
9
9
8
7
6
9
9
9
8
9
8
7
9
8
9
9
8
9
8
7
9
9
9
9
8
9
8
7
9
9
9
8
7
6
9
8
9
8
7
6
5
4
3
2
1
9
9
8
9
9
8
7
6
5
9
9
9
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
1
9
8
7
6
9
9
8
7
6
5
4
3
9
8
9
8
7
6
9
8
7
9
8
7
6
5
9
9
8
7
6
5
4
9
9
9
9
9
9
8
7
6
5
4
3
2
1
9
8
7
9
9
8
7
6
5
4
9
9
8
7
9
8
7
9
8
7
9
8
9
8
7
6
5
4
3
2
1
9
9
8
7
6
5
4
3
2
1
9
9
8
9
9
8
9
8
9
9
8
9
8
7
9
8
7
9
9
9
9
9
8
7
6
9
8
7
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
7
9
8
7
9
8
7
6
5
4
3
2
9
8
7
6
5
4
9
9
9
9
8
9
8
7
6
9
9
8
7
6
5
4
3
9
8
7
9
8
7
6
5
4
3
9
9
9
9
8
9
8
9
8
9
9
8
9
8
7
6
5
4
3
2
9
9
9
8
7
9
8
7
9
9
8
9
8
7
6
9
8
7
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
7
6
9
9
8
7
6
9
9
8
7
6
5
4
9
8
9
8
7
9
9
8
7
6
9
8
7
9
8
7
9
8
7
6
9
8
7
6
5


9
8
7
9
9
8
7
6
5
9
8
7
6
5
4
3
2
9
9
8
7
9
8
7
9
8
9
8
7
9
8
7
9
8
7
9
9
8
7
6
5
4
9
9
9
8
7
6
9
8
9
8
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
1
9
9
9
9
8
7
9
8
9
8
7
9
8
7
9
8
7
6
5
4
3
2
9
9
9
8
7
9
8
9
8
7
9
8
9
8
9
8
7
9
9
8
7
6
5
4
3
2
1
9
9
8
7
9
8
7
9
9
8
7
9
8
7
6
9
8
9
9
8
7
6
5
4
3
2
9
9
9
9
9
8
9
8
7
6
9
9
8
7
6
5
9
8
9
9
9
9
9
8
7
6
5
4
9
8
7
6
5
4
9
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
7
9
9
8
9
9
8
9
9
9
8
9
8
7
9
8
7
6
5
9
9
8
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
9
9
8
7
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
9
8
9
8
9
8
7
6
9
8
7
6
5
4
9
8
7
6
5
4
3
9
9
8
9
9
8
9
9
9
8
9
9
8
9
9
9
8
9
8
7
6
5
9
8
9
9
9
8
7
9
8
7
6
5
9
8
7
9
8
7
6
5
9
8
7
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
9
8
7
6
5
4
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
8
9
8
7
6
5
9
8
7
9
8
7
6
5
4
9
9
9
8
9
8
9
8
9
8
9
8
7
6
5
9
8
9
8
7
6
5
4
3
2
1
9
8
9
9
8
9
8
7
6
9
8
9
8
9
8
7
6
5
4
3
9
8
7
9
8
7
6
5
4
3
9
8
7
9
9
9
8
9
9
9
8
7
6
5
4
3
9
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
8
7
6
9
8
7
9
8
7
6
5
9
8
9
9
9
9
9
9
9
9
8
7
6
5
9
8
7


6
5
4
9
8
7
6
5
4
3
9
8
7
6
9
8
9
9
9
9
8
7
6
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
8
7
6
9
8
7
6
5
9
8
7
6
5
9
9
9
9
9
8
9
8
7
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
7
6
9
9
9
9
8
7
6
5
4
3
2
1
9
9
9
8
9
9
8
7
9
8
7
9
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
7
9
9
9
8
9
8
7
6
5
9
9
9
9
8
9
8
7
9
8
9
8
9
8
7
6
5
4
3
2
9
8
7
6
9
9
9
9
9
8
9
9
8
9
8
9
8
9
9
9
9
8
9
9
9
8
7
6
5
9
8
7
9
8
7
9
8
9
9
9
9
8
7
6
5
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
9
8
7
6
5
4
3
9
8
7
6
5
4
3
9
8
9
8
7
6
9
8
7
6
5
4
3
9
8
7
9
9
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
9
8
9
9
8
9
9
8
9
9
8
7
9
9
8
9
9
8
9
9
8
9
8
7
6
5
4
9
9
9
9
9
8
9
9
8
7
6
5
4
3
2
9
8
7
6
5
9
8
7
6
5
9
9
9
8
7
9
8
7
9
8
7
6
9
8
9
8
7
6
5
4
3
2
1
9
9
8
7
9
9
8
7
9
9
8
7
6
5
4
9
9
9
9
8
7
6
5
4
9
8
7
6
9
8
7
6
5
9
8
7
9
8
7
6
9
9
9
8
7
9
8
7
6
5
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
9
8
9
8
7
6
9
8
7
6
5
4
3
9
9
8
9
9
8
7
6
9
9
8
7
9
8
9
8
7
6
9
8
7
6
5
4
9
8
9
8
9
9
9
8
9
8
9
8
9
8
7
6
5
4
3
9
8
7
9
9
9
8
9
9
8
7
9
9
9
9
8
7
6
5
9
8
9
9


8
9
8
9
9
8
7
9
9
9
9
8
7
6
9
8
7
6
5
4
3
9
8
7
9
8
9
8
9
8
7
6
5
9
8
7
9
9
9
8
7
6
5
4
3
2
1
9
8
7
6
9
8
7
6
5
4
9
8
9
8
9
8
9
8
7
9
8
9
8
7
6
5
9
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
9
9
9
8
7
6
9
9
8
7
9
9
8
9
8
9
9
8
7
6
9
9
9
9
9
9
8
7
6
9
8
9
8
9
9
8
9
8
7
6
5
9
9
9
8
9
8
9
8
7
9
8
7
6
9
8
7
9
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
7
6
5
9
8
9
8
9
8
7
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
8
7
6
5
9
8
9
8
7
6
5
4
9
8
9
9
8
9
8
7
9
8
7
9
8
7
6
9
8
9
8
7
6
9
8
7
6
5
4
3
9
9
9
8
9
8
7
6
9
8
7
9
8
9
8
9
9
8
7
6
9
8
9
8
9
9
8
9
9
9
8
9
8
7
6
5
9
9
8
9
8
7
9
9
9
8
9
8
7
9
8
7
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
9
9
9
8
9
8
9
8
7
6
5
4
3
9
8
7
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
9
9
8
9
8
7
6
9
8
9
8
7
9
8
7
6
5
4
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
9
9
9
9
8
9
8
9
9
9
9
9
9
8
7
6
5
9
9
9
9
8
7
9
9
9
8
7
9
8
7
9
8
7
6
5
4
3
9
8
9
8
9
8
9
8
9
8
7
6
5
9
9
8
7
6
5
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
7
9
9
8
9
8
9
9
9
8
9
8
7
9
8
9
8
7
9
8
9
8
7
9
8
7
6
5
9
9
9
9
8
9
8
7
9
9
8
7
9
9
8
9
8
9


9
8
7
6
5
4
3
9
8
7
6
5
4
3
9
8
7
6
5
9
8
7
6
5
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
9
8
7
9
8
7
6
5
9
8
7
6
5
4
3
9
9
9
9
9
8
7
9
8
7
9
8
7
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
7
9
8
9
9
8
7
6
5
4
3
9
8
9
8
9
8
9
8
9
8
9
8
7
9
8
9
8
7
6
5
4
3
9
9
8
7
6
9
9
8
9
9
8
7
9
9
8
7
6
5
9
9
8
7
6
5
4
3
9
8
7
9
8
9
8
9
8
9
8
7
9
9
8
7
6
5
9
8
9
8
7
6
5
4
3
2
1
9
8
7
6
5
4
3
9
9
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
9
9
8
9
9
8
9
8
7
6
5
4
9
9
8
9
9
9
8
7
9
9
8
7
6
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
9
9
9
9
8
7
6
9
9
8
9
9
9
9
8
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
8
9
9
9
8
7
9
8
9
8
7
6
5
4
3
2
9
9
8
7
6
5
9
9
8
9
9
8
9
8
9
8
7
9
8
9
8
9
8
7
6
9
8
9
8
7
9
8
7
9
8
7
6
5
9
8
9
9
8
9
8
7
6
9
8
9
8
9
8
7
9
8
9
8
7
9
8
7
9
8
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
8
9
8
7
9
8
9
8
7
6
5
9
8
9
8
9
9
9
9
9
8
7
6
5
4
3
2
9
8
7
6
9
8
7
6
5
4
3
9
9
8
9
9
8
9
8
7
6
9
8
9
8
9
8
7
6
5
4
3
2
9
9
9
9
9
8
9
9
8
9
8
7
6
5
9
8
7
9
8
7
6
5
4
3
2
9
9
9
9
9
8
9
9
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
8
9
9
9
8
9


2
1
9
9
8
9
9
9
8
9
8
9
9
8
7
6
5
9
9
9
9
8
7
6
9
9
9
9
8
9
8
7
9
8
7
6
5
4
3
2
1
9
8
9
9
9
8
9
8
7
6
5
9
9
8
9
8
7
6
9
8
7
6
5
4
3
2
1
9
8
9
9
9
9
8
7
9
8
7
6
5
9
8
7
6
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
9
8
7
6
5
4
3
9
8
9
9
9
9
9
8
9
9
8
7
6
9
8
7
9
8
7
6
9
9
9
9
8
7
6
5
9
9
9
8
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
9
9
8
9
8
7
9
9
8
7
6
5
9
8
7
6
5
4
3
9
8
7
9
8
7
6
9
8
7
6
9
8
9
8
9
9
8
9
9
9
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
9
9
8
9
8
7
6
9
8
7
6
5
4
3
9
8
9
9
8
9
9
9
8
7
9
8
9
8
7
6
5
9
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
9
8
9
9
8
7
6
5
9
8
7
6
5
4
3
9
9
9
9
9
9
8
9
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
8
7
9
9
9
8
7
6
5
4
9
9
8
7
6
5
4
3
2
9
9
9
9
8
9
8
9
8
7
6
9
9
9
8
7
6
5
9
8
9
9
8
7
9
8
7
9
8
7
9
8
7
6
5
9
8
7
6
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
9
9
9
9
8
7
6
9
8
9
8
7
6
5
4
3
9
8
7
6
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
7
9
9
8
9
8
7
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
9
9
9
9
8
7
6
5
9
8
7
9
8
9
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
9
8
7
6
5
4
3


7
9
8
9
8
7
6
5
4
3
2
9
9
8
7
6
5
4
9
8
7
6
5
9
8
7
6
9
9
9
9
9
9
8
7
6
5
4
3
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
7
9
9
8
7
6
5
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
8
9
9
9
9
9
8
7
6
5
4
3
9
8
7
6
9
8
9
9
9
9
8
7
9
9
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
8
7
6
9
8
9
9
9
9
9
9
9
8
7
6
5
9
8
9
8
7
6
5
9
8
7
6
9
9
9
9
8
9
8
9
9
8
9
8
7
6
5
4
3
9
8
7
6
5
4
3
9
9
8
9
8
9
9
8
7
6
9
8
7
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
8
7
6
5
4
9
8
9
8
7
9
9
8
7
9
8
9
8
9
9
9
9
9
8
7
6
5
4
9
9
9
9
8
9
9
8
7
6
5
4
3
9
8
7
6
9
9
8
7
6
5
4
3
2
9
9
9
9
8
7
6
5
9
8
7
6
5
9
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
2
9
8
7
9
9
9
9
8
7
9
8
7
9
8
7
6
5
4
3
2
1
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
7
9
9
9
8
9
8
7
9
9
9
8
9
9
9
9
8
9
8
7
9
8
7
9
8
9
8
7
9
9
9
9
8
9
8
9
9
8
7
6
5
4
3
9
9
8
7
9
9
8
9
8
7
6
9
8
7
6
5
4
9
8
9
8
7
6
9
8
7
6
5
9
9
9
8
9
8
7
6
5
9
8
7
6
5
9
8
7
6
9
8
7
6
5
4
3
2
9
8
7
9
8
7
6
5
9
8
7
6
9
9
9
8
7
6
5
9
9
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
7
6
9
9
9
8
9
8
9
9
9
8
7
9
8
9
8
7
6
9
8
7
9
8


9
8
9
9
8
7
9
9
8
9
8
9
9
9
9
8
9
8
9
8
7
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
9
8
7
6
9
9
8
7
6
5
4
9
9
9
8
9
9
9
8
7
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
8
9
8
7
9
8
7
6
5
4
9
9
9
9
8
7
9
8
9
8
7
6
9
8
7
6
9
8
7
6
5
4
9
8
7
6
5
9
8
7
9
9
9
9
8
7
6
5
9
9
8
7
9
8
7
9
9
8
9
8
9
9
8
7
9
9
8
7
6
5
9
9
8
7
9
8
7
6
5
4
3
2
1
9
8
9
9
9
8
7
9
8
7
9
8
7
9
8
7
6
5
4
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
7
9
8
9
8
9
8
7
6
9
8
7
6
5
9
9
9
8
9
9
8
9
9
8
7
9
8
7
9
8
7
6
5
4
3
9
9
9
9
9
9
8
9
8
7
9
8
9
8
7
6
5
4
9
9
9
9
8
7
9
9
8
9
9
9
8
7
6
5
4
3
9
8
7
9
9
9
9
8
7
6
5
4
9
9
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
8
9
8
9
9
9
8
9
9
8
7
6
9
8
9
8
9
9
9
8
7
9
8
9
8
7
6
9
8
7
6
5
4
9
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
8
7
6
9
8
9
9
8
7
6
9
8
7
6
5
9
9
9
9
9
9
8
9
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
7
9
9
8
7
6
5
4
3
9
8
7
6
5
4
9
9
9
9
8
7
9
9
8
9
8
7
9
9
8
7
6
5
4
3
2
1
9
9
8
9
9
9
9
9
8
9
8
7
6
9
8
7
9
9
8
9
8
9
8
7
9
8
9
8
7
9
8
9
8
7
9
8
7
6
5
9
9
9
9
9
9
8
9
8
7


9
9
8
7
9
8
7
6
5
4
9
9
8
9
8
9
9
8
7
6
9
9
9
9
9
9
9
9
9
9
9
9
8
7
6
5
4
3
9
8
7
9
9
9
8
9
9
8
7
6
5
4
9
9
8
9
8
7
6
9
8
7
6
5
4
3
9
8
9
8
9
9
8
9
8
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
9
8
7
6
5
9
8
7
9
9
8
9
8
9
8
9
8
7
6
5
9
8
7
6
5
9
8
7
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
8
9
9
8
9
8
7
6
9
9
9
9
8
9
8
7
9
8
7
6
9
8
7
6
5
4
9
9
8
7
6
5
4
9
8
9
9
9
9
8
9
8
7
9
8
9
8
7
6
5
9
8
7
6
5
9
9
9
8
9
9
9
8
7
6
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
8
7
6
9
8
7
9
8
7
9
8
7
6
5
4
9
9
8
9
9
9
8
9
8
7
9
9
9
8
7
6
5
9
8
9
8
7
9
8
9
9
8
7
9
8
7
9
8
9
8
7
6
9
8
7
6
5
4
3
2
9
9
9
9
8
9
8
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
7
9
8
7
6
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
9
9
8
9
9
9
9
9
9
8
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
7
9
9
9
8
7
6
9
8
7
6
5
4
9
9
9
9
9
8
9
9
8
7
6
5
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
8
9
8
7
6
9
8
9
9
8
9
9
8
9
8
9
8
9
8
9
8
7
6
5
9
8
7
6
5
4
3
2
9
9
9
8
9
9
8
7
6
5
4
9
8
9
8
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
9
9
8
9
8
7
9
9
8
7
9
8
7
6
5
4
3
2
9
8
7
9
9
8
7
6
5
4
3
2
1
9
9
9
9


1
9
9
9
8
9
9
8
9
9
8
7
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
9
9
8
9
9
9
8
7
9
8
9
9
8
7
9
9
8
9
8
9
9
8
7
9
8
7
9
8
7
9
8
7
9
8
9
8
7
6
5
4
3
9
9
9
9
9
8
7
6
9
8
7
6
5
9
8
7
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
8
9
9
9
9
9
9
9
8
9
9
8
7
6
5
9
8
9
9
9
8
9
8
9
8
7
9
8
9
9
9
8
7
6
5
4
3
9
8
7
6
5
4
9
9
9
9
9
8
9
8
7
6
9
8
7
6
9
9
8
7
6
5
4
9
8
9
8
9
8
9
8
7
6
9
8
7
9
8
9
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
9
8
9
8
7
6
9
8
7
9
9
9
9
9
8
9
9
8
7
9
8
7
6
5
4
3
9
8
9
9
8
9
9
9
8
9
8
7
6
5
4
9
9
8
7
6
9
8
7
9
8
9
9
9
8
7
9
9
8
9
8
7
6
5
9
9
8
7
6
5
4
3
2
9
9
8
7
9
8
7
9
8
9
8
9
8
9
8
7
6
9
8
7
6
5
4
3
9
8
7
6
5
4
9
9
9
9
8
9
9
8
7
6
9
8
7
6
5
4
3
2
1
9
9
8
7
6
5
4
3
2
1
9
9
9
8
9
8
7
6
9
9
8
9
8
9
8
7
9
8
7
6
5
4
3
9
9
9
9
9
9
8
7
6
5
9
8
7
6
5
9
8
7
6
5
9
9
9
8
9
9
9
8
9
8
7
9
9
8
9
8
7
6
5
4
3
2
1
9
8
9
9
8
9
8
7
6
9
8
7
6
9
8
7
9
8
7
6
5
4
9
8
7
6
5
9
8
7
6
5
4
9
8
7
9
8
9
9
9
9
9
8
7
6
5
4
3
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
8
9
9
9
8
7
6
9
8
7
6
5
4
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9


3
9
9
9
8
9
9
8
7
6
5
4
3
9
8
9
8
7
6
5
9
8
7
9
8
9
8
7
9
9
8
7
6
5
4
3
9
9
9
8
7
6
5
9
8
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
1
9
8
7
6
5
4
9
9
8
7
9
8
7
9
8
9
8
7
6
5
4
3
9
8
7
6
5
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
8
9
9
9
8
9
8
7
9
8
7
6
9
9
9
9
9
9
9
9
8
9
8
7
6
5
4
3
2
1
9
9
8
9
9
8
7
9
9
8
9
8
7
6
9
9
9
8
7
6
9
8
9
9
9
8
7
9
8
7
9
8
9
8
7
6
5
9
8
7
6
5
4
3
9
9
9
9
9
8
9
8
9
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
1
9
8
9
8
7
6
9
9
8
9
8
7
6
5
4
9
8
7
6
5
4
3
9
8
7
6
5
4
3
9
8
7
6
5
4
3
9
8
7
9
8
7
6
5
4
9
8
9
9
8
7
9
8
7
6
5
9
8
7
6
5
4
3
9
8
7
6
9
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
9
8
7
6
5
9
9
8
7
6
9
8
7
6
5
9
8
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
1
9
9
9
8
7
9
8
9
9
8
7
6
5
9
8
9
8
9
8
7
6
5
4
3
2
9
9
9
9
9
8
7
9
8
9
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
8
9
9
9
9
8
7
9
8
7
6
5
4
9
8
7
6
5
9
8
7
9
8
9
9
8
9
8
7
9
8
9
9
8
7
6
5
4
3
9
9
9
9
9
8
7
9
8
7
6
5
4
9
8
7
9
8
9
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
8
7
9
8
7
9
8
7
9
9
9
8
9
9
8
9
8
9
9
8
7
9
8
7
6
5
4
9
9
9
9
9
8
9
8
7
9
8
7
6
5
4
9


8
7
6
5
9
9
9
9
9
8
9
9
8
7
9
9
8
7
9
8
9
9
8
9
9
9
9
8
7
9
8
9
8
7
6
5
4
3
2
9
9
8
9
8
9
9
8
7
9
8
7
9
8
9
8
7
9
9
8
9
9
9
9
9
8
7
9
8
7
6
5
9
8
7
9
8
7
6
5
4
3
2
9
9
9
8
7
6
9
8
7
6
9
9
8
7
9
8
7
9
8
9
8
7
6
5
4
9
9
8
7
6
5
9
8
9
8
7
6
5
4
9
9
8
7
6
9
8
7
6
5
4
3
2
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
9
8
7
6
5
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
9
9
9
9
9
8
7
9
8
9
8
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
9
9
9
9
9
9
8
7
6
5
4
3
9
8
7
9
8
7
6
9
8
7
6
5
4
9
8
9
8
9
8
7
9
9
8
9
8
7
6
9
8
7
6
5
4
3
9
8
7
6
9
8
7
6
5
4
3
9
9
8
9
8
9
8
7
6
9
8
9
8
7
6
5
9
8
9
8
7
6
5
4
3
2
1
9
9
8
9
9
9
9
9
8
9
8
7
6
5
9
8
7
6
9
9
9
9
9
8
7
9
8
7
9
9
8
9
9
8
7
9
8
9
9
9
9
8
7
9
9
9
8
7
9
9
9
9
9
9
8
7
6
5
4
3
9
9
8
7
6
5
4
3
2
1
9
9
9
9
8
7
9
9
8
7
9
8
9
8
7
9
8
7
6
9
9
8
9
8
9
9
8
9
9
8
7
9
8
7
6
5
4
3
9
9
9
9
8
9
9
9
8
7
9
9
8
7
6
5
4
3
9
8
7
6
5
4
3
2
1
9
9
8
7
9
9
8
9
9
8
7
6
9
8
7
6
5
9
8
7
6
5
9
8
7
6
5
4
3
2
9
9
8
7
9
8
7
9
8
7
6
9
8
7
6
9
8
7
6
5
4
9
9
8
7
9
8
7
6
5
4
3
2
1
9
8
9
8
7
9
8
7
6
9
9
9
8
9
8
7
6
5
9
8
9


9
9
8
9
8
9
9
9
9
8
7
6
5
9
8
9
8
7
6
5
9
9
8
7
6
9
9
9
8
7
9
8
9
9
8
7
9
8
7
6
5
9
9
8
9
8
9
9
8
9
9
8
7
6
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
9
8
7
6
5
9
9
8
7
6
9
9
9
9
8
9
8
9
8
7
9
8
7
9
8
9
9
9
8
9
9
9
8
7
6
5
9
9
8
9
8
7
6
5
4
3
2
1
9
9
8
9
9
9
8
9
9
8
9
8
7
6
9
8
7
6
9
9
9
9
9
9
9
8
7
6
9
8
7
6
5
9
8
7
6
5
4
3
9
8
9
8
9
9
9
8
7
6
9
9
9
8
9
8
9
8
9
8
7
9
8
9
8
9
9
8
7
6
5
4
3
2
9
8
7
6
5
9
8
7
9
8
7
6
5
4
3
9
8
7
6
9
9
9
8
9
8
7
6
9
8
7
9
8
7
9
8
7
9
8
7
6
5
4
3
2
1
9
9
9
9
9
9
8
9
8
7
6
9
8
7
9
8
7
6
5
4
3
2
9
9
9
9
9
9
9
8
9
8
7
9
8
7
6
5
4
9
9
9
8
7
9
9
9
9
8
7
9
8
7
6
5
9
8
7
9
9
9
8
7
9
9
9
9
8
7
6
5
9
8
7
6
5
4
9
8
7
9
8
9
9
9
8
7
6
5
9
8
9
9
9
8
7
6
5
4
9
8
7
6
5
4
3
2
1
9
9
8
9
9
8
9
9
8
7
6
5
9
9
8
7
9
8
7
6
5
9
9
9
9
9
9
9
8
7
9
8
7
6
5
4
3
2
1
9
8
7
6
5
4
9
9
9
8
7
9
9
9
9
8
7
6
5
9
8
7
6
5
4
3
2
1
9
9
9
9
9
8
9
8
9
8
7
9
8
7
9
8
7
6
5
9
9
9
9
8
9
8
9
8
9
8
7
6
5
4
9
8
7
6
9
8
7
6
5
9
9
9
9
8
9
9
8
7
6
5
9
8
7
6
9
8
7
6
5
9
8
7
6
5
4
9
8
7
9
8
7
9
8
7
9
8
7
6
5


KeyboardInterrupt: 

In [ ]:
                    #for k in [0,3,6]:
                        #for m in [0,3,6]:
                            #b = board[k:k+3,k:k+3].flatten()
                            #if 0<sum([len(b[b==i])>1 for i in range(1,10)]):
                                #max_num-=1
                                #nums_to_try.remove(num)    

In [171]:
board

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [127]:
board

array([[5., 8., 2., 9., 4., 7., 1., 3., 6.],
       [6., 4., 3., 1., 8., 9., 2., 5., 7.],
       [3., 6., 1., 2., 7., 8., 4., 9., 5.],
       [7., 3., 8., 5., 6., 2., 9., 4., 1.],
       [1., 9., 5., 7., 2., 4., 3., 6., 8.],
       [9., 5., 6., 8., 1., 3., 7., 2., 4.],
       [4., 7., 9., 3., 5., 1., 6., 8., 2.],
       [8., 2., 7., 4., 9., 6., 5., 1., 3.],
       [2., 1., 4., 6., 3., 5., 8., 7., 9.]])

In [125]:
board[0:3,0:3]

array([[5., 8., 2.],
       [6., 4., 3.],
       [3., 6., 1.]])

In [141]:
board[0:3,3:6]

array([[9., 4., 7.],
       [1., 8., 9.],
       [2., 7., 8.]])

In [147]:
for i in [0,3,6]:
    for j in [0,3,6]:
        b = board[i:i+3,i:i+3].flatten()
        print(sum([len(b[b==i])>1 for i in range(1,10)]))

2
2
2
1
1
1
1
1
1


In [131]:
board[0:3,6:9]

array([[1., 3., 6.],
       [2., 5., 7.],
       [4., 9., 5.]])

In [133]:
board[3:6,0:3]

array([[7., 3., 8.],
       [1., 9., 5.],
       [9., 5., 6.]])

In [164]:
b=[]
for i in [0,3,6]:
    for j in [0,3,6]:
        b.append(list(board[i:i+3,i:i+3].flatten())) 

In [168]:
np.array(b).flatten()

array([5., 8., 2., 6., 4., 3., 3., 6., 1., 5., 8., 2., 6., 4., 3., 3., 6.,
       1., 5., 8., 2., 6., 4., 3., 3., 6., 1., 5., 6., 2., 7., 2., 4., 8.,
       1., 3., 5., 6., 2., 7., 2., 4., 8., 1., 3., 5., 6., 2., 7., 2., 4.,
       8., 1., 3., 6., 8., 2., 5., 1., 3., 8., 7., 9., 6., 8., 2., 5., 1.,
       3., 8., 7., 9., 6., 8., 2., 5., 1., 3., 8., 7., 9.])

In [182]:
# import pygame library
import pygame

# initialise the pygame font
pygame.font.init()

# Total window
screen = pygame.display.set_mode((500, 600))

# Title and Icon
pygame.display.set_caption("SUDOKU SOLVER USING BACKTRACKING")
#img = pygame.image.load('icon.png')
#pygame.display.set_icon(img)

x = 0
y = 0
dif = 500 / 9
val = 0
# Default Sudoku Board.
grid =[
		[7, 8, 0, 4, 0, 0, 1, 2, 0],
		[6, 0, 0, 0, 7, 5, 0, 0, 9],
		[0, 0, 0, 6, 0, 1, 0, 7, 8],
		[0, 0, 7, 0, 4, 0, 2, 6, 0],
		[0, 0, 1, 0, 5, 0, 9, 3, 0],
		[9, 0, 4, 0, 6, 0, 0, 0, 5],
		[0, 7, 0, 3, 0, 0, 0, 1, 2],
		[1, 2, 0, 0, 0, 7, 4, 0, 0],
		[0, 4, 9, 2, 0, 6, 0, 0, 7]
	]

# Load test fonts for future use
font1 = pygame.font.SysFont("comicsans", 40)
font2 = pygame.font.SysFont("comicsans", 20)
def get_cord(pos):
	global x
	x = pos[0]//dif
	global y
	y = pos[1]//dif

# Highlight the cell selected
def draw_box():
	for i in range(2):
		pygame.draw.line(screen, (255, 0, 0), (x * dif-3, (y + i)*dif), (x * dif + dif + 3, (y + i)*dif), 7)
		pygame.draw.line(screen, (255, 0, 0), ( (x + i)* dif, y * dif ), ((x + i) * dif, y * dif + dif), 7)

# Function to draw required lines for making Sudoku grid		
def draw():
	# Draw the lines
		
	for i in range (9):
		for j in range (9):
			if grid[i][j]!= 0:

				# Fill blue color in already numbered grid
				pygame.draw.rect(screen, (0, 153, 153), (i * dif, j * dif, dif + 1, dif + 1))

				# Fill grid with default numbers specified
				text1 = font1.render(str(grid[i][j]), 1, (0, 0, 0))
				screen.blit(text1, (i * dif + 15, j * dif + 15))
	# Draw lines horizontally and verticallyto form grid		
	for i in range(10):
		if i % 3 == 0 :
			thick = 7
		else:
			thick = 1
		pygame.draw.line(screen, (0, 0, 0), (0, i * dif), (500, i * dif), thick)
		pygame.draw.line(screen, (0, 0, 0), (i * dif, 0), (i * dif, 500), thick)	

# Fill value entered in cell	
def draw_val(val):
	text1 = font1.render(str(val), 1, (0, 0, 0))
	screen.blit(text1, (x * dif + 15, y * dif + 15))

# Raise error when wrong value entered
def raise_error1():
	text1 = font1.render("WRONG !!!", 1, (0, 0, 0))
	screen.blit(text1, (20, 570))
def raise_error2():
	text1 = font1.render("Wrong !!! Not a valid Key", 1, (0, 0, 0))
	screen.blit(text1, (20, 570))

# Check if the value entered in board is valid
def valid(m, i, j, val):
	for it in range(9):
		if m[i][it]== val:
			return False
		if m[it][j]== val:
			return False
	it = i//3
	jt = j//3
	for i in range(it * 3, it * 3 + 3):
		for j in range (jt * 3, jt * 3 + 3):
			if m[i][j]== val:
				return False
	return True

# Solves the sudoku board using Backtracking Algorithm
def solve(grid, i, j):
	
	while grid[i][j]!= 0:
		if i<8:
			i+= 1
		elif i == 8 and j<8:
			i = 0
			j+= 1
		elif i == 8 and j == 8:
			return True
	pygame.event.pump()
	for it in range(1, 10):
		if valid(grid, i, j, it)== True:
			grid[i][j]= it
			global x, y
			x = i
			y = j
			# white color background\
			screen.fill((255, 255, 255))
			draw()
			draw_box()
			pygame.display.update()
			pygame.time.delay(20)
			if solve(grid, i, j)== 1:
				return True
			else:
				grid[i][j]= 0
			# white color background\
			screen.fill((255, 255, 255))
		
			draw()
			draw_box()
			pygame.display.update()
			pygame.time.delay(50)
	return False

# Display instruction for the game
def instruction():
	text1 = font2.render("PRESS D TO RESET TO DEFAULT / R TO EMPTY", 1, (0, 0, 0))
	text2 = font2.render("ENTER VALUES AND PRESS ENTER TO VISUALIZE", 1, (0, 0, 0))
	screen.blit(text1, (20, 520))	
	screen.blit(text2, (20, 540))

# Display options when solved
def result():
	text1 = font1.render("FINISHED PRESS R or D", 1, (0, 0, 0))
	screen.blit(text1, (20, 570))
run = True
flag1 = 0
flag2 = 0
rs = 0
error = 0
# The loop thats keep the window running
while run:
	
	# White color background
	screen.fill((255, 255, 255))
	# Loop through the events stored in event.get()
	for event in pygame.event.get():
		# Quit the game window
		if event.type == pygame.QUIT:
			run = False
		# Get the mouse position to insert number
		if event.type == pygame.MOUSEBUTTONDOWN:
			flag1 = 1
			pos = pygame.mouse.get_pos()
			get_cord(pos)
		# Get the number to be inserted if key pressed
		if event.type == pygame.KEYDOWN:
			if event.key == pygame.K_LEFT:
				x-= 1
				flag1 = 1
			if event.key == pygame.K_RIGHT:
				x+= 1
				flag1 = 1
			if event.key == pygame.K_UP:
				y-= 1
				flag1 = 1
			if event.key == pygame.K_DOWN:
				y+= 1
				flag1 = 1
			if event.key == pygame.K_1:
				val = 1
			if event.key == pygame.K_2:
				val = 2
			if event.key == pygame.K_3:
				val = 3
			if event.key == pygame.K_4:
				val = 4
			if event.key == pygame.K_5:
				val = 5
			if event.key == pygame.K_6:
				val = 6
			if event.key == pygame.K_7:
				val = 7
			if event.key == pygame.K_8:
				val = 8
			if event.key == pygame.K_9:
				val = 9
			if event.key == pygame.K_RETURN:
				flag2 = 1
			# If R pressed clear the sudoku board
			if event.key == pygame.K_r:
				rs = 0
				error = 0
				flag2 = 0
				grid =[
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0],
				[0, 0, 0, 0, 0, 0, 0, 0, 0]
				]
			# If D is pressed reset the board to default
			if event.key == pygame.K_d:
				rs = 0
				error = 0
				flag2 = 0
				grid =[
					[7, 8, 0, 4, 0, 0, 1, 2, 0],
					[6, 0, 0, 0, 7, 5, 0, 0, 9],
					[0, 0, 0, 6, 0, 1, 0, 7, 8],
					[0, 0, 7, 0, 4, 0, 2, 6, 0],
					[0, 0, 1, 0, 5, 0, 9, 3, 0],
					[9, 0, 4, 0, 6, 0, 0, 0, 5],
					[0, 7, 0, 3, 0, 0, 0, 1, 2],
					[1, 2, 0, 0, 0, 7, 4, 0, 0],
					[0, 4, 9, 2, 0, 6, 0, 0, 7]
				]
	if flag2 == 1:
		if solve(grid, 0, 0)== False:
			error = 1
		else:
			rs = 1
		flag2 = 0
	if val != 0:		
		draw_val(val)
		# print(x)
		# print(y)
		if valid(grid, int(x), int(y), val)== True:
			grid[int(x)][int(y)]= val
			flag1 = 0
		else:
			grid[int(x)][int(y)]= 0
			raise_error2()
		val = 0
	
	if error == 1:
		raise_error1()
	if rs == 1:
		result()	
	draw()
	if flag1 == 1:
		draw_box()	
	instruction()

	# Update window
	pygame.display.update()

# Quit pygame window
pygame.quit()	
	


KeyboardInterrupt: 

In [179]:
pip install pygame

     |████████████████████████████████| 8.9 MB 1.7 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [187]:
base  = 3
side  = base*base

# pattern for a baseline valid solution
def pattern(r,c): 
    return (base*(r%base)+r//base+c)%side

# randomize rows, columns and numbers (of valid base pattern)
from random import sample

def shuffle(s): 
    return sample(s,len(s)) 

rBase = range(base) 
rows  = [ g*base + r for g in shuffle(rBase) for r in shuffle(rBase) ] 
cols  = [ g*base + c for g in shuffle(rBase) for c in shuffle(rBase) ]
nums  = shuffle(range(1,base*base+1))

# produce board using randomized baseline pattern
board = [ [nums[pattern(r,c)] for c in cols] for r in rows ]

for line in board:
    print(line)


[4, 8, 1, 7, 2, 9, 6, 5, 3]
[6, 5, 3, 1, 4, 8, 2, 9, 7]
[2, 9, 7, 3, 6, 5, 4, 8, 1]
[8, 1, 2, 6, 9, 7, 5, 3, 4]
[9, 7, 6, 4, 5, 3, 8, 1, 2]
[5, 3, 4, 2, 8, 1, 9, 7, 6]
[1, 2, 9, 5, 7, 6, 3, 4, 8]
[3, 4, 8, 9, 1, 2, 7, 6, 5]
[7, 6, 5, 8, 3, 4, 1, 2, 9]


In [230]:
lst = list()
for i in range(100000):
    nums = 0
    for i in range(100):
        one = np.random.randint(0,101)
        two = np.random.randint(0,101)

        if one==two:
            nums+=1
    lst.append(nums)
sum(lst)/len(lst)

0.99487

In [ ]:
634110640